name: Execute R Notebook

on:
  workflow_dispatch:

jobs:
  run_r_notebook:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Realizar checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Configurar R en el runner
    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0' # Cambia según la versión que necesites

    # Paso 3: Instalar dependencias necesarias para ejecutar el notebook
    - name: Install R packages
      run: |
        Rscript -e 'install.packages("IRkernel", repos="https://cloud.r-project.org/")'
        Rscript -e 'IRkernel::installspec()' # Configurar el kernel de R si es necesario
        Rscript -e 'install.packages(c("tidyverse", "readr"), repos="https://cloud.r-project.org/")'

    # Paso 4: Ejecutar el notebook
    - name: Execute R Notebook
      run: |
        cd artefactos
        Rscript -e "rmarkdown::render('analisis exploratorio de datos.ipynb')"
