name: Ejecutar Analisis Exploratorio Manualmente

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        required: false

jobs:
  run_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Aunque no usaremos Python directamente, nbconvert está en PyPI

      - name: Install R and IRkernel
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base
          R -e "install.packages('IRkernel', repos='http://cran.rstudio.com/'); IRkernel::installspec()"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert pandoc

      - name: Navigate to artifacts and run notebook
        run: |
          cd artefactos
          jupyter nbconvert --to notebook --execute --inplace --ExecutePreprocessor.kernel_name=ir "analisis exploratorio de datos.ipynb"

      - name: Check if files exist
        run: |
          cd artefactos
          if [ ! -f "datos_combinados.csv" ] || [ ! -f "analisis exploratorio de datos.ipynb" ]; then
            echo "Faltan archivos necesarios."
            exit 1
          else
            echo "Archivos encontrados."
          fi

      - name: Convert notebook to HTML for review
        run: |
          cd artefactos
          jupyter nbconvert "analisis exploratorio de datos.ipynb" --to html --ExecutePreprocessor.kernel_name=ir

      - name: Upload HTML results
        uses: actions/upload-artifact@v4
        with:
          name: html-notebook
          path: artefactos/"analisis exploratorio de datos.html"
