name: Ejecutar Analisis Exploratorio

on:
  push:
    branches:
      - main  # o la rama que quieras
  pull_request:
    branches:
      - main

jobs:
  run_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # o la versión de Python que necesites

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas numpy matplotlib nbconvert

      - name: Navigate to artifacts and run notebook
        run: |
          cd artefactos
          jupyter nbconvert --to notebook --execute --inplace "analisis exploratorio de datos.ipynb"

      - name: Check if files exist
        run: |
          cd artefactos
          if [ ! -f "datos_combinados.csv" ] || [ ! -f "analisis exploratorio de datos.ipynb" ]; then
            echo "Faltan archivos necesarios."
            exit 1
          else
            echo "Archivos encontrados."
          fi

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: executed-notebook
          path: artefactos/"analisis exploratorio de datos.ipynb"
