name: Create Release Without Token

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Generar artefacto
      - name: Build Artifact
        run: |
          mkdir -p build
          echo "Contenido de ejemplo para el release" > build/artifact.txt
          zip -r build/artifact.zip build/

      # Crear el tag (si no existe)
      - name: Create Tag
        run: |
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}

      # Subir el artefacto manualmente (opcional)
      - name: Notify
        run: echo "Por favor, sube el artefacto manualmente al release en GitHub."
