name: Create Release Without Token

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Generar artefacto
      - name: Build Artifact
        run: |
          mkdir -p build
          echo "Contenido de ejemplo para el release" > build/artifact.txt
          zip -r build/artifact.zip build/

      # Notificar que el tag ya existe
      - name: Notify
        run: echo "El tag ${{ github.ref_name }} ya existe. Continuando con el proceso."
