name: Create Automatic Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Generar el artefacto
      - name: Build Artifact
        run: |
          mkdir -p build
          echo "Contenido de ejemplo para el release" > build/artifact.txt
          zip -r build/artifact.zip build/

      # Crear el release automáticamente
      - name: Create GitHub Release
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "tag_name": "'${{ github.ref_name }}'",
            "target_commitish": "main",
            "name": "Release '${{ github.ref_name }}'",
            "body": "Automated release notes for '${{ github.ref_name }}'.",
            "draft": false,
            "prerelease": false
          }' \
          https://api.github.com/repos/${{ github.repository }}/releases

      # Subir el artefacto al release
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/artifact.zip
          asset_name: artifact.zip
          asset_content_type: application/zip
